name: pichub
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  firebase_analytics: ^7.1.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.19.2+1
  fzregex: ^1.0.3
  google_fonts: ^1.1.1
  google_mobile_ads: ^0.11.0+4
  http: ^0.12.2
  lottie: ^0.7.0+1
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_rename_app: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/Icon.png"

flutter_rename_app:
  application_name: pichub
  dart_package_name: pichub
  application_id: com.fz.pichub
  bundle_id: com.fz.pichub
  android_package_name: com.fz.pichub

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/webp/
    - assets/json/
    - i18n/
